workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 120
    environment:
      flutter: 3.27.4
      xcode: 16.3
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Получение зависимостей
        script: flutter pub get

      - name: Генерация iOS артефактов
        script: flutter build ios --no-codesign --debug

      - name: Повторный pod install (отладка)
        script: |
          echo "=== Содержимое ios/ перед pod install ==="
          ls -la ios/
          echo "=== Запуск pod install ==="
          cd ios
          pod install --verbose
          cd ..
      
      - name: Настройка подписи
        script: xcode-project use-profiles

      - name: Сборка IPA
        script: flutter build ipa --release --export-options-plist="ios/ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
