workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 120  # Увеличиваем таймаут
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка проекта
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
    
      - name: Создание базового iOS-проекта
        script: |
          # Создаем минимальную структуру iOS-проекта
          flutter create --platforms=ios --no-overwrite .
    
      - name: Генерация podhelper.rb
        script: |
          # Генерируем iOS-специфичные файлы
          flutter build ios --no-codesign --debug
          cp -f .ios/Flutter/podhelper.rb ios/Flutter/ || true
    
      - name: Проверка файлов
        script: |
          echo "Файлы в ios/Flutter:"
          ls -la ios/Flutter/
          [ -f "ios/Flutter/podhelper.rb" ] || exit 1
    
      - name: Установка CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      
      - name: Настройка подписи
        script: xcode-project use-profiles

      - name: Сборка IPA
        script: flutter build ipa --release --export-options-plist="ios/ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa