workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка и подготовка
        script: |
          flutter clean
          flutter pub get

      - name: Генерация iOS проекта
        script: flutter build ios --release  # Убрали --no-codesign!

      - name: Проверка podhelper.rb
        script: |
          if [ -f "ios/Flutter/podhelper.rb" ]; then  # Правильный путь
            echo "✅ podhelper.rb найден"
          else
            echo "❌ ОШИБКА: podhelper.rb не найден"
            exit 1
          fi

      - name: Установка CocoaPods зависимостей
        script: |
          cd ios
          pod install --repo-update  # Обновляем репозиторий
          cd ..

      - name: Настройка подписи
        script: xcode-project use-profiles

      - name: Декодирование GoogleService-Info.plist
        script: echo $GOOGLESERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Сборка IPA
        script: flutter build ipa --release --export-options-plist="ios/ExportOptions.plist"  # Указать путь к plist

    artifacts:
      - build/ios/ipa/*.ipa