workflows:
  build-ios:
    name: iOS Release Build
    working_directory: .
    max_build_duration: 120
    environment:
      flutter: 3.27.4
      xcode: 15.3
      cocoapods: default
      vars:
        distribution_type: development
        bundle_identifier: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка проекта
        script: |
          echo "=== Очистка проекта ==="
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
    
      - name: Получение зависимостей Flutter
        script: |
          echo "=== Получение зависимостей Flutter ==="
          flutter pub get
    
      - name: Сборка Flutter без подписи (генерация iOS-проектов)
        script: |
          echo "=== Flutter build (no codesign) ==="
          flutter build ios --release --no-codesign
    
      - name: Установка зависимостей CocoaPods
        script: |
          echo "=== Установка зависимостей CocoaPods ==="
          cd ios
          pod install --repo-update
          cd ..
    
      - name: Архивация IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive CODE_SIGNING_ALLOWED=NO
    
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     -exportPath build/ios/ipa \
                     -exportOptionsPlist ExportOptions.plist \
    
                     CODE_SIGNING_ALLOWED=NO
    post_build:
      - name: 🔍 Вывод дерева проекта
        script: |
          echo "📁 Структура проекта после сборки:"
          find . -print
        always_run: true
                         
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Pods/Manifest.lock