workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 120
    environment:
      flutter: 3.27.4
      xcode: 16.3
      vars:
        distribution_type: development
        bundle_identifier: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка проекта
        script: |
          echo "=== Очистка проекта ==="
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Получение зависимостей Flutter
        script: |
          echo "=== Получение зависимостей Flutter ==="
          flutter pub get

      - name: Установка зависимостей CocoaPods
        script: |
          echo "=== Установка зависимостей CocoaPods ==="
          cd ios
          pod install --repo-update
          cd ..

      - name: Сборка IPA
        script: |
          echo "=== Сборка IPA ==="
          flutter build ipa --release --export-options-plist="ios/ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Pods/Manifest.lock