workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Получение зависимостей
        script: flutter pub get

      - name: Генерация iOS и podhelper.rb
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      - name: Отладка podhelper.rb
        script: |
          echo "Содержимое директории .ios/Flutter:"
          ls -la .ios/Flutter/
          
          if [ -f .ios/Flutter/podhelper.rb ]; then
            echo "Содержимое podhelper.rb:"
            cat .ios/Flutter/podhelper.rb
          else
            echo "Файл podhelper.rb не найден!"
          fi

      - name: Декодируем GoogleService-Info.plist
        script: echo $GOOGLESERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Настройка подписи
        script: xcode-project use-profiles

      - name: Сборка IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log