workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.example.kittyWorries" # заменишь своим
      code_signing:
        certificates:
          - certificate_name: "iApps_Cert" # замените на ваш Reference name
            certificate_password: "iApps0101"  # если применимо
        provisioning_profiles:
          - profile_name: "iApps_Pro"
      groups:
        - firebase_credentials
    scripts:
      - name: Установка зависимостей
        script: |
          flutter pub get
      - name: Генерация GoogleService-Info.plist
        script: |
          echo $GOOGLESERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Настройка подписания в Xcode
        script: |
          xcode-project use-profiles
      - name: Вывод содержимого export_options.plist
        script: cat /Users/builder/export_options.plist
      - name: Сборка iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
