workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials
    scripts:

      - name: Получение Dart-зависимостей
        script: flutter pub get

      #- name: Обновление CocoaPods
        #script: |
          #cd ios
          #pod repo update    # актуализируем specs
          #pod install   

      - name: Декодируем GoogleService-Info.plist
        script: echo $GOOGLESERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      
      - name: Настройка подписи Xcode
        script: xcode-project use-profiles

      - name: Сборка IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
