workflows:
  build-ios:
    name: iOS Release Build
    max_build_duration: 120
    environment:
      flutter: 3.27.4
      xcode: 16.3
      vars:
        BUNDLE_ID: "ankit.appsinst.indjag"
      ios_signing:
        certificates:
          - kitty_cert
        provisioning_profiles:
          - Mob_prov
      groups:
        - firebase_credentials

    scripts:
      - name: Очистка проекта
        script: |
          echo "=== Очистка проекта ==="
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Установка CocoaPods
        script: |
          echo "=== Установка/обновление CocoaPods ==="
          gem install cocoapods
          cd ios
          pod install --repo-update
          cd ..

      - name: Получение зависимостей Flutter
        script: |
          echo "=== Получение зависимостей Flutter ==="
          flutter pub get

      - name: Генерация iOS артефактов
        script: |
          echo "=== Генерация iOS артефактов ==="
          flutter build ios --no-codesign --release

      - name: Подробный pod install
        script: |
          echo "=== Подробный pod install ==="
          cd ios
          pod install --verbose | tee ../logs/pod_install.log
          cd ..

      - name: Настройка профилей подписи
        script: |
          echo "=== Настройка профилей подписи ==="
          xcode-project use-profiles

      - name: Сборка IPA
        script: |
          echo "=== Сборка IPA ==="
          flutter build ipa --release --export-options-plist="ios/ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - logs/**/*.log
      - ios/Pods/Manifest.lock