name: kitty_worries
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
      sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.1.0
  path_provider: ^2.1.2
  table_calendar: ^3.1.3
  flutter_local_notifications: ^19.1.0
  intl: ^0.19.0
  timezone: ^0.10.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true