name: kitty_worries
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
    generate: true
  provider: ^6.1.0
  path_provider: ^2.1.2
  table_calendar: ^3.1.3
  intl: ^0.19.0
  timezone: ^0.10.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  googleapis_auth: ^1.4.0
  http: ^1.3.0
  permission_handler: ^11.0.0
  awesome_notifications: ^0.10.0
  foundation: ^0.0.5
  flutter_localizations:
      sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/services/service-account.json