// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH1JXBKlHJOHngxZjBw65WmTrxaYhfWNY',
    appId: '1:1042085303110:web:b33dfc1166ed8c0af94b47',
    messagingSenderId: '1042085303110',
    projectId: 'kitty-worries',
    authDomain: 'kitty-worries.firebaseapp.com',
    databaseURL: 'https://kitty-worries-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitty-worries.firebasestorage.app',
    measurementId: 'G-LCRBX6Q11Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZnOlbwL1yGY4vjzMdqSmVwnXyPJPC6YQ',
    appId: '1:1042085303110:android:c4de1126790e10caf94b47',
    messagingSenderId: '1042085303110',
    projectId: 'kitty-worries',
    databaseURL: 'https://kitty-worries-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitty-worries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHP_hV2kbhl8aE-tWIHBtzdHH7oJri5o',
    appId: '1:1042085303110:ios:93d68a31b7d2cec7f94b47',
    messagingSenderId: '1042085303110',
    projectId: 'kitty-worries',
    databaseURL: 'https://kitty-worries-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitty-worries.firebasestorage.app',
    iosBundleId: 'ankit.appsinst.indjag.kittyWorries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH1JXBKlHJOHngxZjBw65WmTrxaYhfWNY',
    appId: '1:1042085303110:web:a253acd1b3ba7c54f94b47',
    messagingSenderId: '1042085303110',
    projectId: 'kitty-worries',
    authDomain: 'kitty-worries.firebaseapp.com',
    databaseURL: 'https://kitty-worries-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitty-worries.firebasestorage.app',
    measurementId: 'G-S9N0DKDN6B',
  );
}
