platform :ios, '13.0'

ENV['FLUTTER_FRAMEWORK_DIR'] = File.join(__dir__, 'Flutter')

# если FLUTTER_ROOT не задано, находим его через flutter
ENV['FLUTTER_ROOT'] ||= `flutter sdk-path`.strip

require File.expand_path(
  File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb'),
  __dir__,
)

target 'Runner' do
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
