flutter_root = ENV['FLUTTER_ROOT']
flutter_application_path = '.'

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

platform :ios, '17.0'
use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end